#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\DefaultController:Index
    methods: GET
lunch:
    path: /lunch
    methods: POST
    controller: App\Controller\LunchController:Index